/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : KIOSK
 #	author : miyako
 #	2017/03/10
 #
 # --------------------------------------------------------------------------------*/



// --- KIOSK
void KIOSK_SET_MODE(sLONG_PTR *pResult, PackagePtr pParams);
void KIOSK_Get_mode(sLONG_PTR *pResult, PackagePtr pParams);

#define KIOSK_ON	1
#define KIOSK_OFF	0

#if VERSIONWIN
#include "Shlwapi.h"
#pragma comment (lib, "Shlwapi.lib")
#define HKCU HKEY_CURRENT_USER
LPCWSTR KEY_DisableTaskMgr = L"Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System";
LPCWSTR VAL_DisableTaskMgr = L"DisableTaskMgr";
#endif